config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create, :edit, :update, :destroy] do
    member do
      get :user_owner_data
    end
  end
  resources :projects, only: [:new, :create, :edit, :update, :destroy] do
    member do
      get :add_users
      get :project_owner_data
    end
  end
  resources :conversations, only: [:new, :create, :show, :destroy]
  resources :messages, only: [:create, :destroy]
  resources :requests, only: [:new, :create, :update]
  resources :invites, only: [:new, :create, :destroy]
  resources :user_projects, only: [:update, :destroy]
  resources :subscriptions, only: [:new, :create, :edit, :update, :destroy]
  resources :tiers, only: [:index]
  resources :password_recoveries, only: [:new, :create] do
    member do
      get :check
      post :verify
    end
  end
  resources :bans, only: [:new, :create, :update]
  resources :tasks, only: [:create, :update, :destroy] do
    member do
      put :transfer
    end
  end
  resources :claims, only: [:create, :destroy]
  resources :settings, only: [:update]

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get '/mb-login' => 'sessions#mb_new'
  get '/splash' => 'sessions#splash'
  get '/home' => 'users#home'
  get '/message_box' => 'users#message_box'
  get '/mb-new-project' => 'users#mb_new_project'
  get '/typeahead' => 'users#typeahead'
  get '/owner-data' => 'users#owner_data'
  get '/users-data' => 'users#users_data'
  get '/projects-data' => 'projects#projects_data'
  get '/validate' => 'users#validate'
  get '/support' => 'static#support'
  get '/features' => 'static#features'
  get '/lazy_load' => 'conversations#lazy_load'
  post '/add_user' => 'conversations#add_user'
  get '/plugin-info' => 'users#plugin_info'
  get '/app-messages' => 'conversations#app_messages'
  post '/read-messages' => 'conversations#read_messages'
  get '/search' => 'conversations#search'
  get '/upgrade' => 'tiers#upgrade'
  get '/pricing' => 'tiers#pricing'

  root 'users#home'
end

app/models/message.rb
class Message < ActiveRecord::Base
  include ActionView::Helpers::DateHelper

  belongs_to :conversation
  belongs_to :user
  has_many :message_users
  has_many :recipients, through: :message_users, source: :user
  has_one :task
  has_many :attachments

  validates :user_id, :conversation_id, :content, presence: true

  def content_preview(length)
    content.length > length ? "#{content[0...length]}..." : content[0...length]
  end

  def date_to_s
     created_at.strftime('%A, %B %d')
  end

  def time_to_s
    created_at.strftime('%l:%M%P')
  end

  def time_ago_to_s
    "#{distance_of_time_in_words(DateTime.now, created_at)} ago"
  end

  def set_json
    json = {}
    json[:content] = content
    json[:user_name] = user.name
    json
  end

  def from_user?(checked_user)
    user.id == checked_user.id
  end

  def read(recipient)
    message_user = message_user_by_user(recipient)
    message_user.update_attribute(:read, true) if message_user
  end

  def is_read_by?(checked_user)
    message_user = message_user_by_user(checked_user)
    message_user ? message_user.read : true
  end

  def message_user_by_user(recipient)
    message_users.find_by(user_id: recipient.id)
  end

  def auto_linked_content
    Rinku.auto_link(content, :all, 'target="_blank"')
  end

  def is_recent?(inactive_time)
    created_at > DateTime.now - inactive_time.minutes
  end

  def delete_old_task
    task.delete if task
  end

  def has_task?
    task ? task.persisted? : false
  end

  def self.recent_count_by_days(number)
    where("created_at > ?", DateTime.now - number.days).count
  end

  def self.recent_non_owner_count_by_days(number)
    where("created_at > ?", DateTime.now - number.days).select(&:not_from_owner).count
  end

  def not_from_owner
    !from_owner
  end

  def from_owner
    user.owner
  end

  def has_attachments?
    attachments.size > 0
  end

  def default_content
    assign_attributes(content: "(No Content)") if content.empty?
  end

  def self.search(query)
    where("lower(content) LIKE ?", "#{query.downcase}")
  end

  def self.task_search(query)
    search(query).includes(:task).where(tasks: { id: nil })
  end
end

app/models/tier.rb
class Tier < ActiveRecord::Base
  has_many :users

  validates :name, :admin_projects, :users_per_project, presence: true
  validates :name, uniqueness: true

  def permit_user_project(admin)
    admin.active_admin_projects.length < admin_projects
  end

  def permit_project_user(project)
    project.invited_users_count < users_per_project
  end

  def self.all_published
    all.where(published: true)
  end

  def find_subscription_by_type(yearly)
    yearly ? yearly_id : monthly_id
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    current_user.update_last_online
    @message = Message.new(message_params)
    @message.default_content

    if @message.valid?
      redirect_to home_path and return unless current_user.is_member_of_project?(@message.conversation.project)
      @message.save!
      set_up_recipients
      set_up_task if params[:tasks]
      set_up_attachments(params[:message][:files]) if params[:message][:files]
      @message.conversation.users.each do |user|
        user == current_user ? current_conversation = @message.conversation : current_conversation = nil
        Pusher.trigger("conversation#{@message.conversation.token}#{user.id}", 'new-message', {
          user_id: @message.user.id,
          conversation_token: @message.conversation.token,
          current_user_html: (render_to_string partial: "messages/current_user_message", locals: { message: @message, task: @message.task }),
          other_user_html: (render_to_string partial: "messages/other_user_message", locals: { message: @message, task: @message.task }),
          task_html: task_html(user),
          note_html: note_html,
          notes_html: (render_to_string partial: "conversations/notes_card", locals: { conversation: @message.conversation, current_conversation: current_conversation, project: @message.conversation.project, user: user }),
          conversation_id: @message.conversation.id,
          project_id: @message.conversation.project.id,
          app_html: (render_to_string partial: "conversations/app_card", locals: { conversation: @message.conversation, current_conversation: current_conversation, project: @message.conversation.project, user: user })
        })
      end

      new_message_emails

      if request.xhr?
        render partial: "messages/message", locals: { message: @message }
      else
        redirect_to home_path(project_id: @message.conversation.project.id, conversation_id: @message.conversation.id)
      end

    else
      flash[:warn] = "Unable to create message, please try again"
      redirect_to :back
    end
  end

  def destroy
    @message = Message.find_by(id: params[:id])
    conversation = @message.conversation

    if @message.destroy
      if request.xhr?
        render json: {
          id: conversation.id,
          html: (render_to_string partial: "conversations/notes_card", locals: { conversation: conversation, current_conversation: conversation, project: conversation.project, user: current_user })
        }
      else
        redirect_to home_path
      end
    else
      flash[:warn] = "Unable to delete message, please try again"
    end
  end

  private

  def message_params
    params.require(:message).permit(:content, :user_id, :conversation_id)
  end

  def set_up_recipients
    @message.conversation.other_users(current_user).each do |user|
      MessageUser.create(
        user_id: user.id,
        message_id: @message.id
      )
    end
  end

  def set_up_task
    @task = Task.create(message_id: @message.id)
  end

  def task_html(user)
    return false unless @message.task
    (render_to_string partial: "tasks/task", locals: { task: @message.task, message: @message, user: user } )
  end

  def note_html
    (render_to_string partial: "messages/note", locals: { message: @message } )
  end

  def new_message_emails
    if @message.task
      new_task_emails
    else
      @message.conversation.other_users(current_user).each do |user|
        UserMailer.new_message_email(@message, user).deliver_now if user.needs_notification?(@message)
      end
    end
  end

  def new_task_emails
    @message.conversation.other_users(current_user).each do |user|
      UserMailer.new_task_email(@message.task, user).deliver_now if user.needs_task_notification?(@message.task)
    end
  end

  def set_up_attachments(files)
    invalid_files = params[:invalid_files].split(",").map(&:to_i)
    files.each_with_index do |file, index|
      unless invalid_files.include?(index)
        obj = S3_BUCKET.object(file.original_filename)

        obj.upload_file(file.tempfile, acl:'public-read')

        attachment = Attachment.new(url: obj.public_url, message_id: @message.id, name: file.original_filename)
        unless attachment.save
          flash[:warn] = "There was a problem uploading your image, please try again"
          redirect_to :back
        end
      end
    end
  end
end

app/views/messages/_current_user_message.html.erb
<div class="self-msg-wrapper" id="message-<%= message.id %>">
  <small class="self-meta-data text-right u-full-width"><b>Me</b> <i><%= message.time_ago_to_s %></i></small>
  <% if message.user.image %>
    <img class="profile-pic" src="<%= message.user.image_url %>">
  <% else %>
    <div class="profile-pic has-no-pic"><div class="table-cell"><%= message.user.first_name[0] %></div></div>
  <% end %>
  <% if task %>
    <p class="self-pwd <%= task.html_class %>">
  <% else %>
    <p class="self-pwd">
  <% end %>
    <%= sanitize(simple_format(message.auto_linked_content.gsub(/(?:\n\r?|\r\n?)/, '<br>')), :tags => %w(br a)) %>

    <% if message.has_attachments? %>
      <span class="attachments">
        <% message.attachments.each do |attachment| %>
          <%= link_to attachment.url, class: "ellipsis", target: "_blank" do %>
            <%= attachment.name %>
            <% if attachment.is_image? %>
              <%= image_tag attachment.url %>
            <% end %>
          <% end %>
        <% end %>
      </span>
    <% end %>

  </p>
  <div class="icon-bar self">
    <% if task %>

      <% if task.completer %>
        <%= link_to task_path(message.task, task: { completer_id: nil }), title: "Mark as Incomplete", method: "PUT", class: "uncomplete-task" do %>
          <i class="fa fa-undo"></i>
        <% end %>
      <% else %>
        <%= link_to root_path(tasks: true,  project_id: message.conversation.project.id, user_ids: message.conversation.user_ids, anchor: "task-#{task.id}"), title: "View in tasks list" do %>
            <i class="fa fa-eye"></i>
        <% end %>

        <%= link_to task_path(message.task, task: { completer_id: current_user.id }), title: "Mark as Complete", method: "PUT", class: "complete-task" do %>
          <i class="fa fa-check-circle"></i>
        <% end %>
      <% end %>

      <%= link_to task_path(message.task), title: "Remove Task", method: "DELETE", class: "remove-model" do %>
        <i class="fa fa-minus-circle"></i>
      <% end %>

    <% else %>

      <%= link_to tasks_path(task: { message_id: message.id } ), title: "Add Task", method: "POST", class: "new-model" do %>
        <i class="fa fa-exclamation-circle"></i>
      <% end %>

    <% end %>
  </div>
</div>

app/views/messages/_form.html.erb
<%= form_for message, html: { id: "av-message-form" } do |f| %>
  <div>
    <% if tasks %>
      <%= f.text_area :content, placeholder: "Type task here...", value: "" %>
    <% elsif notes %>
      <%= f.text_area :content, placeholder: "Type note here...", value: "" %>
    <% else %>
      <%= f.text_area :content, placeholder: "Type message here...", value: "" %>
    <% end %>

    <div class="file-wrapper">
      <%= f.label :files do %>
        <i class="fa fa-paperclip"></i>
      <% end %>

      <%= f.file_field :files, multiple: true %>
    </div>
  </div>

  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.hidden_field :conversation_id, value: conversation.id %>
  <% if tasks %>
    <%= hidden_field_tag :tasks, tasks %>
  <% end %>
  <%= button_tag(class: "button button-message") do %>
    <i class="fa fa-paper-plane"></i>
  <% end %>
<% end %>

app/views/messages/_message.html.erb
<% if message.from_user?(current_user) %>
  <%= render partial: "messages/current_user_message", locals: { message: message, task: message.task } %>
<% else %>
  <%= render partial: "messages/other_user_message", locals: { message: message, task: message.task } %>
<% end %>

app/views/messages/_note.html.erb
<div class="note" id="note-<%= message.id %>">
  <div class="note-icons u-pull-right">
    <%= link_to message_path(message), method: "DELETE", class: "remove-notes", title: "Delete this note" do %>
      <i class="fa fa-times"></i>
    <% end %>
  </div>

  <p>
    <small><i><%= message.time_ago_to_s %></i></small>
  </p>
  <% if message.has_task? %>
    <p class="<%= message.task.html_class %>"><%= message.content %></p>
  <% else %>
    <p><%= message.content %></p>
  <% end %>
  <div class="icon-bar">
    <% if message.has_task? %>
      <% if message.task.completer %>

        <%= link_to task_path(message.task, task: { completer_id: nil }), title: "Mark as Incomplete", method: "PUT", class: "uncomplete-task" do %>
          <i class="fa fa-undo"></i>
        <% end %>

      <% else %>
        <%= link_to task_path(message.task, task: { completer_id: current_user.id }), title: "Mark as Complete", method: "PUT", class: "complete-task" do %>
          <i class="fa fa-check-circle"></i>
        <% end %>

        <%= link_to task_path(message.task), title: "Remove Task", method: "DELETE", class: "remove-model" do %>
          <i class="fa fa-minus-circle"></i>
        <% end %>
      <% end %>

    <% else %>
      <%= link_to tasks_path(task: { message_id: message.id } ), title: "Add Task", method: "POST", class: "new-model" do %>
        <i class="fa fa-exclamation-circle"></i>
      <% end %>
    <% end %>
  </div>
</div>

app/views/messages/_other_user_message.html.erb
<div class="them-msg-wrapper" id="message-<%= message.id %>">

<% if message.user.image %>
  <img class="profile-pic" src="<%= message.user.image_url %>">
<% else %>
  <div class="profile-pic has-no-pic"><div class="table-cell"><%= message.user.first_name[0] %></div></div>
<% end %>
<small class="u-full-width them-meta-data"><b><%= message.user.first_name_last_initial %></b> <i><%= message.time_ago_to_s %></i></small>
  <% if task %>
    <p class="<%= task.html_class %>">
      <%= sanitize(simple_format(message.auto_linked_content.gsub(/(?:\n\r?|\r\n?)/, '<br>')), :tags => %w(br a)) %>

      <% if message.has_attachments? %>
        <span class="attachments">
          <% message.attachments.each do |attachment| %>
            <%= link_to attachment.url, class: "ellipsis", target: "_blank" do %>
              <%= attachment.name %>
              <% if attachment.is_image? %>
                <%= image_tag attachment.url %>
              <% end %>
            <% end %>
          <% end %>
        </span>
      <% end %>

    </p>
  <% else %>
    <p>
      <%= sanitize(simple_format(message.auto_linked_content.gsub(/(?:\n\r?|\r\n?)/, '<br>')), :tags => %w(br a)) %>

      <% if message.has_attachments? %>
        <span class="attachments">
          <% message.attachments.each do |attachment| %>
            <%= link_to attachment.url, class: "ellipsis", target: "_blank" do %>
              <%= attachment.name %>
              <% if attachment.is_image? %>
                <%= image_tag attachment.url %>
              <% end %>
            <% end %>
          <% end %>
        </span>
      <% end %>
    </p>

  <% end %>

  <div class="icon-bar them">
    <% if task %>

      <% if task.completer %>
        <%= link_to task_path(message.task, task: { completer_id: nil }), title: "Mark as Incomplete", method: "PUT", class: "uncomplete-task" do %>
          <i class="fa fa-undo"></i>
        <% end %>
      <% else %>
        <%= link_to root_path(tasks: true, title: "View in tasks list", project_id: message.conversation.project.id, user_ids: message.conversation.user_ids, anchor: "task-#{task.id}") do %>
            <i class="fa fa-eye"></i>
        <% end %>

        <%= link_to task_path(message.task, task: { completer_id: current_user.id }), title: "Mark as Complete", method: "PUT", class: "complete-task" do %>
          <i class="fa fa-check-circle"></i>
        <% end %>
      <% end %>

    <% end %>
  </div>
</div>