config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create, :edit, :update, :destroy] do
    member do
      get :user_owner_data
    end
  end
  resources :projects, only: [:new, :create, :edit, :update, :destroy] do
    member do
      get :add_users
      get :project_owner_data
    end
  end
  resources :conversations, only: [:new, :create, :show, :destroy]
  resources :messages, only: [:create, :destroy]
  resources :requests, only: [:new, :create, :update]
  resources :invites, only: [:new, :create, :destroy]
  resources :user_projects, only: [:update, :destroy]
  resources :subscriptions, only: [:new, :create, :edit, :update, :destroy]
  resources :tiers, only: [:index]
  resources :password_recoveries, only: [:new, :create] do
    member do
      get :check
      post :verify
    end
  end
  resources :bans, only: [:new, :create, :update]
  resources :tasks, only: [:create, :update, :destroy] do
    member do
      put :transfer
    end
  end
  resources :claims, only: [:create, :destroy]
  resources :settings, only: [:update]

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get '/mb-login' => 'sessions#mb_new'
  get '/splash' => 'sessions#splash'
  get '/home' => 'users#home'
  get '/message_box' => 'users#message_box'
  get '/mb-new-project' => 'users#mb_new_project'
  get '/typeahead' => 'users#typeahead'
  get '/owner-data' => 'users#owner_data'
  get '/users-data' => 'users#users_data'
  get '/projects-data' => 'projects#projects_data'
  get '/validate' => 'users#validate'
  get '/support' => 'static#support'
  get '/features' => 'static#features'
  get '/lazy_load' => 'conversations#lazy_load'
  post '/add_user' => 'conversations#add_user'
  get '/plugin-info' => 'users#plugin_info'
  get '/app-messages' => 'conversations#app_messages'
  post '/read-messages' => 'conversations#read_messages'
  get '/search' => 'conversations#search'
  get '/upgrade' => 'tiers#upgrade'
  get '/pricing' => 'tiers#pricing'

  root 'users#home'
end

app/models/task.rb
class Task < ActiveRecord::Base
  include ActionView::Helpers::DateHelper

  belongs_to :message
  belongs_to :completer, class_name: "User"
  has_many :claims

  def has_claims?
    claims.size > 0
  end

  def status
    completer ? "Complete Task" : "Incomplete Task"
  end

  def html_class
    completer ? "complete" : "incomplete"
  end

  def user
    message.user
  end

  def content
    message.content
  end

  def from_recent_message?(inactive_time)
    message.is_recent?(inactive_time)
  end

  def complete?
    completer_id != nil
  end

  def incomplete?
    !complete?
  end

  def completed_date_s
    "#{distance_of_time_in_words(DateTime.now, updated_at)} ago by #{completer.name}"
  end

  def abbreviated_claim_names
    "#{claims[0..1].map(&:user_name).join(", ")}#{extra_claim_names}"
  end

  def extra_claim_names
    claims.size > 2 ? " and #{claims.size - 2} more" : ""
  end

  def claim_text
    claims.size > 1 ? "#{abbreviated_claim_names} are working on this" : "#{abbreviated_claim_names} is working on this"
  end

  def update_conversation(conversation_id)
    message.update_attributes(conversation_id: conversation_id)
  end

  def delete_claims
    claims.each(&:delete)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :task_by_id, only: [:update, :destroy, :transfer]

  def create
    redirect_to :back and return if existing_task?
    @task = Task.new(task_params)

    if @task.valid?
      @task.save
      fire_pusher_event(@task.id, @task.message, @task.message.conversation.users, true, false)
      new_task_emails
    else
      flash[:warn] = "Unable to create task"
    end

    redirect_to :back
  end

  def update
    @task.assign_attributes(task_params)

    if @task.valid?
      @task.save
      fire_pusher_event(@task.id, @task.message, @task.message.conversation.users, false, false)
      completed_task_emails if @task.completed
    else
      flash[:warn] = "Unable to update task"
    end

    if request.xhr?
      render text: "Done"
    else
      redirect_to :back
    end
  end

  def destroy
    if @task
      task_id = @task.id
      message = @task.message
      users = @task.message.conversation.users
      @task.delete_claims
      @task.delete
      fire_pusher_event(task_id, message, users, false, true)
    else
      flash[:warn] = "No task by that id"
    end

    if request.xhr?
      render text: "Done"
    else
      redirect_to :back
    end
  end

  def transfer
    old_convo_id = @task.message.conversation.id
    @task.update_conversation(params[:conversation_id])
    @task.delete_claims
    fire_pusher_transfer(old_convo_id)

    render text: "Done"
  end

  private

  def task_params
    params.require(:task).permit(:message_id, :completer_id)
  end

  def task_by_id
    @task = Task.find_by(id: params[:id])
  end

  def fire_pusher_event(task_id, message, users, new_record, deleted)
    task = Task.find_by(id: task_id)
    users.each do |user|
      user == current_user ? current_conversation = message.conversation : current_conversation = nil
      Pusher.trigger("task#{message.conversation.token}#{user.id}", 'new-task', {
        message_id: message.id,
        task_id: task_id,
        user_id: message.user.id,
        conversation_token: message.conversation.token,
        conversation_id: message.conversation.id,
        current_user_html: (render_to_string partial: "messages/current_user_message", locals: { message: message, task: task }),
        other_user_html: (render_to_string partial: "messages/other_user_message", locals: { message: message, task: task }),
        task_html: task_html(task, user),
        note_html: note_html(message),
        notes_html: (render_to_string partial: "conversations/notes_card", locals: { conversation: message.conversation, current_conversation: current_conversation, project: message.conversation.project, user: user }),
        deleted: deleted,
        completer_id: task ? task.completer_id : false,
        completed_tasks_count: message.conversation.completed_tasks.count,
        app_html: (render_to_string partial: "conversations/app_card", locals: { conversation: message.conversation, current_conversation: current_conversation, project: message.conversation.project, user: user })
      })
    end
  end

  def fire_pusher_transfer(old_convo_id)
    old_convo = Conversation.find_by(id: old_convo_id)
    users = old_convo.users
    users.each do |user|
      user == current_user ? current_conversation = old_convo : current_conversation = nil
      Pusher.trigger("transferOldTask#{old_convo.token}#{user.id}", 'transfer-old-task', {
        task_id: @task.id,
        message_id: @task.message.id,
        convo_id: old_convo_id,
        convo_token: old_convo.token,
        app_html: (render_to_string partial: "conversations/app_card", locals: { conversation: old_convo, current_conversation: current_conversation, project: old_convo.project, user: user }
        ),
        notes_html: (render_to_string partial: "conversations/notes_card", locals: { conversation: old_convo, current_conversation: current_conversation, project: old_convo.project, user: user }
        )
      })
    end

    users = @task.message.conversation.users
    users.each do |user|
      user == current_user ? current_conversation = old_convo : current_conversation = nil

      Pusher.trigger("transferNewTask#{@task.message.conversation.token}#{user.id}", 'transfer-new-task', {
        task_id: @task.id,
        message_id: @task.message.id,
        convo_id: @task.message.conversation.id,
        convo_token: @task.message.conversation.token,
        app_html: (render_to_string partial: "conversations/app_card", locals: { conversation: @task.message.conversation, current_conversation: current_conversation, project: @task.message.conversation.project, user: user }
        ),
        notes_html: (render_to_string partial: "conversations/notes_card", locals: { conversation: @task.message.conversation, current_conversation: current_conversation, project: @task.message.conversation.project, user: user }
        ),
        task_html: task_html(@task, user)
      })
    end
  end

  def task_html(task, user)
    task ? (render_to_string partial: "tasks/task", locals: { task: task, message: task.message, user: user } ) : ""
  end

  def note_html(message)
    (render_to_string partial: "messages/note", locals: { message: message } )
  end

  def new_task_emails
    @task.message.conversation.other_users(current_user).each do |user|
      UserMailer.new_task_email(@task, user).deliver_now if user.needs_task_notification?(@task)
    end
  end

  def completed_task_emails
    @task.message.conversation.other_users(current_user).each do |user|
      UserMailer.completed_task_email(@task, user).deliver_now if user.needs_task_notification?(@task)
    end
  end

  def existing_task?
    message = Message.find_by(id: params[:task][:message_id])
    message ? message.task : false
  end
end

app/views/tasks/_task.html.erb
<div class="task-container" id="task-<%= task.id %>">
  <div class="task-icons u-pull-right">
    <% if user == message.user %>
      <i class="fa fa-exchange transfer-icon" title="Transfer task to another conversation"></i>
    <% end %>
    <!-- claim icons -->
    <% if task.incomplete? %>
      <% if user.claimed?(task) %>
        <%= link_to claim_path(user.claim_from_task(task)), method: "DELETE", class: "remove-model", title: "Remove claim on this task" do %>
          <i class="fa fa-cog user-claimed spin"></i>
        <% end %>
      <% elsif task.has_claims? %>
        <%= link_to claims_path(claim: { user_id: user.id, task_id: task.id }), method: "POST", class: "new-model", title: "Claim this task" do %>
          <i class="fa fa-cog claimed spin"></i>
        <% end %>
      <% else %>
        <%= link_to claims_path(claim: { user_id: user.id, task_id: task.id }), method: "POST", class: "new-model", title: "Claim this task" do %>
          <i class="fa fa-cog unclaimed hover-spin"></i>
        <% end %>
      <% end %>
    <% end %>
    <!-- end claim icons -->
    <%= link_to task_path(task), method: "DELETE", class: "remove-model", title: "Remove task" do %>
      <i class="fa fa-times"></i>
    <% end %>
  </div>
  <small><b><%= task.user.first_name_last_initial %></b> <i><%= message.time_ago_to_s %></i></small>
  <div class="task-item content">
    <% if task.completer_id %>
      <%= link_to task_path(task, task: { completer_id: nil }), method: "PUT", class: "uncomplete-task", title: "Mark task as not done" do %>
        <div class="task-item icon complete"></div>
      <% end %>
      <p>
        <%= sanitize(simple_format(message.auto_linked_content.gsub(/(?:\n\r?|\r\n?)/, '<br>')), :tags => %w(br a)) %><br>
      </p>

      <p class="task-no-left">
        <small>Completed <%= task.completed_date_s %></small>
      </p>

    <% else %>
      <%= link_to task_path(task, task: { completer_id: user.id }), method: "PUT", class: "complete-task", title: "Mark task as done" do %>
        <div class="task-item icon pending"></div>
      <% end %>

      <p>
        <%= sanitize(simple_format(message.auto_linked_content.gsub(/(?:\n\r?|\r\n?)/, '<br>')), :tags => %w(br a)) %>
      </p>

      <% if task.has_claims? %>
        <p class="task-no-left">
          <small><%= task.claim_text %></small>
        </p>
      <% end %>
    <% end %>
  </div>

  <% if message.has_attachments? %>
    <span class="attachments task-attachments">
      <% message.attachments.each do |attachment| %>
        <%= link_to attachment.url, class: "task-attachment ellipsis", target: "_blank" do %>
          <%= attachment.name %>
          <% if attachment.is_image? %>
            <%= image_tag attachment.url %>
          <% end %>
        <% end %>
      <% end %>
    </span>
  <% end %>
</div>