config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create, :edit, :update, :destroy] do
    member do
      get :user_owner_data
    end
  end
  resources :projects, only: [:new, :create, :edit, :update, :destroy] do
    member do
      get :add_users
      get :project_owner_data
    end
  end
  resources :conversations, only: [:new, :create, :show, :destroy]
  resources :messages, only: [:create, :destroy]
  resources :requests, only: [:new, :create, :update]
  resources :invites, only: [:new, :create, :destroy]
  resources :user_projects, only: [:update, :destroy]
  resources :subscriptions, only: [:new, :create, :edit, :update, :destroy]
  resources :tiers, only: [:index]
  resources :password_recoveries, only: [:new, :create] do
    member do
      get :check
      post :verify
    end
  end
  resources :bans, only: [:new, :create, :update]
  resources :tasks, only: [:create, :update, :destroy] do
    member do
      put :transfer
    end
  end
  resources :claims, only: [:create, :destroy]
  resources :settings, only: [:update]

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get '/mb-login' => 'sessions#mb_new'
  get '/splash' => 'sessions#splash'
  get '/home' => 'users#home'
  get '/message_box' => 'users#message_box'
  get '/mb-new-project' => 'users#mb_new_project'
  get '/typeahead' => 'users#typeahead'
  get '/owner-data' => 'users#owner_data'
  get '/users-data' => 'users#users_data'
  get '/projects-data' => 'projects#projects_data'
  get '/validate' => 'users#validate'
  get '/support' => 'static#support'
  get '/features' => 'static#features'
  get '/lazy_load' => 'conversations#lazy_load'
  post '/add_user' => 'conversations#add_user'
  get '/plugin-info' => 'users#plugin_info'
  get '/app-messages' => 'conversations#app_messages'
  post '/read-messages' => 'conversations#read_messages'
  get '/search' => 'conversations#search'
  get '/upgrade' => 'tiers#upgrade'
  get '/pricing' => 'tiers#pricing'

  root 'users#home'
end

app/models/request.rb
class Request < ActiveRecord::Base
  belongs_to :user
  belongs_to :project

  validates :user_id, :project_id, presence: true
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  def new
    @project = token_project(params[:token])
    @request = current_user.pending_request_by_project(@project) || Request.new
  end

  def create
    @request = Request.new(request_params)

    if current_user.can_send_request(@request)
      @request.save
      flash[:notice] = "Request sent"
    else
      flash[:warn] = "Unable to send request, please try again"
    end

    redirect_to :back
  end

  def update
    @request = Request.find_by(id: params[:id])
    @request.assign_attributes(request_params)

    if @request.valid?
      @request.save
      set_up_user if params[:request][:approved]
      flash[:notice] = "Request updated"
    else
      flash[:warn] = "Unable to update request, please try again"
    end

    redirect_to :back
  end

  private

  def request_params
    params.require(:request).permit(:user_id, :project_id, :active)
  end

  def set_up_user
    UserProject.create(
      user_id: @request.user.id,
      project_id: @request.project.id,
      admin: false
    )
  end
end

app/views/requests/_card.html.erb
<div class="request-card">
  <h4><%= request.user.name %></h4>
  <%= link_to "Deny", request_path(request, request: { active: false, approved: false }), method: "PUT", class: 'button button-primary' %>
  <%= link_to "Accept", request_path(request, request: { active: false, approved: true }), method: "PUT", class: 'button button-primary' %>
</div>

app/views/requests/_form.html.erb
    <div class="mb-body text-center msg-bx-padding">
      <% if request.new_record? %>
      <h4>
        Click below request to be added by the project owner
      </h4>
      <p>Once the project owner approves, you can start using the app immediately</p>
  <%= form_for request do |f| %>
    <%= f.hidden_field :user_id, value: current_user.id %>
    <%= f.hidden_field :project_id, value: project.id %>

    <%= f.submit "Send Request", class: "button button-primary" %>
    <% end %>
<% else %>
  <h4 class="text-center">Request has been sent!</h4>
  <p>Please allow some time for this request to be processed</p>
<% end %>

app/views/requests/_typeahead.html.erb
<%= form_for my_request, html: { class: 'typeahead-form', id: "request-typeahead" } do |f| %>
  <%= text_field_tag :project_id, nil, class: "typeahead app-view-typeahead request-typeahead", value: "", placeholder: "Search Evia Projects" %>

  <%= f.hidden_field :project_id, value: nil %>
  <%= f.hidden_field :user_id, value: current_user.id %>
<% end %>

app/views/requests/new.html.erb
<%= javascript_include_tag "message_box/message_box" %>
<div id="msg-bx">
	 <!--# Message Box Header #-->
    <header class="mb-header">
      <p>
        <% if current_user.has_unread_conversations? %>
          <span class="is-unread-mb"> &bull; </span> &nbsp;
        <% end %>
        <%= link_to login_path, target: '_blank' do %>
          <span class="evia-font">Evia</span>
        <% end %>
|       <%= current_user.name %>
        <span id="mb-header_icons">
        <% if current_user.has_unread_conversations_other_projects?(@project) %>
          <i class="fa fa-globe is-unread-icon" id="projects-btn"></i>
        <% else %>
          <i class="fa fa-globe" id="projects-btn"></i>
        <% end %>
          <i class="fa fa-user" id="acct-btn"></i>
        </span>
      </p>
    </header>
    <!--# END Message Box Header #-->


      <!--# projects Dropdown #-->
      <div id="mb-projects-dropdown" class="mb-dropdown mb-projects-request-dropdown">
        <p><b>Your projects</b></p>
        <ul id='project-list'>
          <% current_user.projects.each do |project| %>
            <li>
              <% if @project == project %>
                <%= link_to project.name, home_path, target: '_blank', class: 'is-active' %>
              <% else %>
                <% if current_user.has_unread_conversations_by_project?(project) %>
                  <%= link_to project.name, home_path, target: '_blank', class: 'is-unread-project' %>
                <% else %>
                  <%= link_to project.name, home_path, target: '_blank' %>
                <% end %>
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>
      <!--# END projects Dropdown #-->

      <!--# projects Dropdown #-->
      <div id="mb-acct-dropdown" class="mb-dropdown">
        <p><b>Your Account</b></p>
        <ul id='acct-list'>
          <li>
            <%= link_to 'Dashboard', login_path, target: '_blank' %>
          </li>
          <li>
            <%= link_to 'Edit Account', edit_user_path(current_user), target: '_blank' %>
          </li>
          <li>
            <%= link_to 'Upgrade', edit_user_path(current_user), target: '_blank' %>
          </li>
          <li>
            <%= link_to 'Log Out', logout_path(message_box: true, token: @project.token) %>
          </li>
        </ul>
      </div>
      <!--# END projects Dropdown #-->



			<%= render partial: "form", locals: { request: @request, project: @project } %>

		</div>
	</div>
</div>