config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create, :edit, :update, :destroy] do
    member do
      get :user_owner_data
    end
  end
  resources :projects, only: [:new, :create, :edit, :update, :destroy] do
    member do
      get :add_users
      get :project_owner_data
    end
  end
  resources :conversations, only: [:new, :create, :show, :destroy]
  resources :messages, only: [:create, :destroy]
  resources :requests, only: [:new, :create, :update]
  resources :invites, only: [:new, :create, :destroy]
  resources :user_projects, only: [:update, :destroy]
  resources :subscriptions, only: [:new, :create, :edit, :update, :destroy]
  resources :tiers, only: [:index]
  resources :password_recoveries, only: [:new, :create] do
    member do
      get :check
      post :verify
    end
  end
  resources :bans, only: [:new, :create, :update]
  resources :tasks, only: [:create, :update, :destroy] do
    member do
      put :transfer
    end
  end
  resources :claims, only: [:create, :destroy]
  resources :settings, only: [:update]

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get '/mb-login' => 'sessions#mb_new'
  get '/splash' => 'sessions#splash'
  get '/home' => 'users#home'
  get '/message_box' => 'users#message_box'
  get '/mb-new-project' => 'users#mb_new_project'
  get '/typeahead' => 'users#typeahead'
  get '/owner-data' => 'users#owner_data'
  get '/users-data' => 'users#users_data'
  get '/projects-data' => 'projects#projects_data'
  get '/validate' => 'users#validate'
  get '/support' => 'static#support'
  get '/features' => 'static#features'
  get '/lazy_load' => 'conversations#lazy_load'
  post '/add_user' => 'conversations#add_user'
  get '/plugin-info' => 'users#plugin_info'
  get '/app-messages' => 'conversations#app_messages'
  post '/read-messages' => 'conversations#read_messages'
  get '/search' => 'conversations#search'
  get '/upgrade' => 'tiers#upgrade'
  get '/pricing' => 'tiers#pricing'

  root 'users#home'
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_secure_token

  has_many :conversations
  has_many :user_projects
  has_many :users, through: :user_projects
  has_many :requests
  has_many :invites
  has_many :tasks, through: :conversations

  validates :name, presence: true

  def has_conversations?
    conversations.count > 0
  end

  def other_users(user)
    users.where.not(id: user.id)
  end

  def has_other_users?(user)
    other_users(user).count > 0
  end

  def non_member_users
    User.where.not(id: user_ids)
  end

  def find_conversation_by_users(users)
    conversations.find { |conversation| conversation.user_ids.sort == users.map(&:id).sort }
  end

  def ordered_conversations
    conversations.sort_by { |conversation| conversation.messages.last.updated_at }.reverse!
  end

  def find_admin
    user_projects.find_by(admin: true)
  end

  def typeahead_users_data(conversation, user)
    conversation.other_project_users.map(&:typeahead_data)
  end

  def non_member_users_data
    non_member_users.map(&:typeahead_data)
  end

  def pending_requests
    requests.where(active: true)
  end

  def has_pending_requests?
    pending_requests.count > 0
  end

  def has_alert?(user)
    has_pending_requests? || user.has_unread_conversations_by_project?(self)
  end

  def self.all_projects_data
    all.map(&:typeahead_data)
  end

  def typeahead_data
    { name: name, id: id }
  end

  def non_owner_users
    users.where(owner: false)
  end

  def incomplete_tasks
    tasks.where(completed: false)
  end

  def completed_tasks
    conversations.collect(&:completed_tasks)
  end

  def has_completed_tasks?
    completed_tasks > 0
  end

  def pending_tasks
    conversations.collect(&:pending_tasks)
  end

  def has_pending_tasks?
    pending_tasks > 0
  end

  def find_notes(user)
    conversations.find { |conversation| conversation.user_ids == [user.id] }
  end

  def creation_date
    created_at.strftime("%m/%d/%Y")
  end

  def has_invites?
    invites.count > 0
  end

  def invited_users_count
    non_owner_users.size + invites.count
  end
end

app/models/tier.rb
class Tier < ActiveRecord::Base
  has_many :users

  validates :name, :admin_projects, :users_per_project, presence: true
  validates :name, uniqueness: true

  def permit_user_project(admin)
    admin.active_admin_projects.length < admin_projects
  end

  def permit_project_user(project)
    project.invited_users_count < users_per_project
  end

  def self.all_published
    all.where(published: true)
  end

  def find_subscription_by_type(yearly)
    yearly ? yearly_id : monthly_id
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :project_by_id, only: [:edit, :update, :add_users, :destroy, :project_owner_data]

  def new
    @project = Project.new
  end

  def create
    if current_user.can_create_project
      @project = Project.new(project_params)

      if @project.valid?
        @project.save
        set_up_user
        send_project_email
        flash[:notice] = "Project successfully created"
        redirect_to home_path(project_id: @project.id)
      else
        flash[:warn] = "Unable to create project, please try again"
        redirect_to :back
      end
    else
      flash[:warn] = "You've reached the project limit for your current tier of service. Please upgrade and try again."
      redirect_to :back
    end
  end

  def edit

  end

  def update
    @project.assign_attributes(project_params)

    if @project.valid?
      @project.save
      flash[:notice] = "Project successfully saved"

      redirect_to home_path(project_id: @project.id)
    else
      flash[:warn] = "Unable to save updates to project, please try again"
      redirect_to :back
    end
  end

  def destroy
    if @project
      @project.delete
      flash[:notice] = "Project deleted"
    else
      flash[:warn] = "Unable to delete project, please try again"
    end

    redirect_to home_path
  end

  def add_users
  end

  def projects_data
    @projects = Project.all.order(id: :desc)
  end

  def project_owner_data

  end

  private

  def project_by_id
    @project = Project.find_by(id: params[:id])
  end

  def project_params
    params.require(:project).permit(:name, :url, :active)
  end

  def set_up_user
    UserProject.create(
      user_id: current_user.id,
      project_id: @project.id,
      admin: true,
      approved: true
    )
  end

  def set_up_notification(user_id, project)
    Notification.create(
      user_id: user_id,
      content: "You have been added to the project #{@project.name} by #{current_user.name}"
    )
  end

  def send_project_email
    UserMailer.project_email(current_user, @project).deliver_now
  end
end

app/views/projects/_form.html.erb
<%= form_for project do |f| %>
  <div>
    <%= f.text_field :name, placeholder: "Project Name" %> &nbsp;
  </div>

  <%= f.hidden_field :user_id, value: current_user.id %>

  <div style="margin-top:10px">
    <%= f.submit class: "button button-primary" %>
  </div>
<% end %>

app/views/projects/_project_data.html.erb
<div class="project-data-partial">
  <h5><%= project.name %></h5>
  <p>Admin: <%= user.admin_of_project?(project) %></p>
  <p>Total Conversations: <%= user.conversations_by_project(project).count %></p>
  <p>Total Messages: <%= user.messages_by_project(project).count %></p>
</div>

app/views/projects/add_users.html.erb
<div class="background-class">
	<div class="container">
		<div class="row">
			<div class="six offset-by-three columns text-center">
				<h1>Awesome! Let's add a new user to this project</h1>
				<%= form_for @project do |f| %>
<div>
    <%= f.label :user_ids, "Add Users" %>
    <%= f.collection_select(:user_ids, User.all_other_users(current_user), :id, :name,{}, {:multiple => true}) %>
</div>
<div>
    <%= f.submit%>
  </div>
<% end %>
			</div>
		</div>
	</div>
</div>

app/views/projects/edit.html.erb
<%= render partial: "form", locals: { project: @project } %>

app/views/projects/new.html.erb
<div class="project-form-container">
  <span>
    <div class="hidden-text">
      <h1>Create Your Project</h1>
      <!-- <h4>Go ahead and create your first adminisrtative project!</h4>-->
      <h4>Messaging on Evia revolves around <strong><em>a project</em></strong>, invite team <br>members and clients to become part of your project.</h4>
      <!-- <h4>You will be emailed your unique project token. Use it to activate our <br>WordPress Plugin for even more messaging power</h4> -->
      <p>This is an optional step, you can create a project at anytime!</p>
      <br>
    </div>
    <%= render partial: "form", locals: { project: @project } %>
    <br>
    <%= link_to "Skip for Now", home_path %>
  </span>
</div>

app/views/projects/project_owner_data.html.erb
<%= render partial: "layouts/admin_header" %>

<section>
  <div class="container">
    <div class="row">
      <div class="twelve columns">
        <h3><%= @project.name %> Data</h3>
        <h5>Users</h5>
        <table>
          <thead>
            <tr>
              <th>ID</th>
              <th>Name</th>
              <th>Username</th>
              <th>Email</th>
              <th>Admin?</th>
              <th>Total Conversations on <%= @project.name %></th>
              <th>Total Messages on <%= @project.name %></th>
            </tr>
          </thead>
          <tbody>
            <% @project.users.each do |user| %>
              <tr>
                <td><%= user.id %></td>
                <td><%= link_to user.name, user_owner_data_user_path(user) %></td>
                <td><%= user.username %></td>
                <td><%= user.email %></td>
                <td>
                  <%= user.admin_of_project?(@project) %>
                  <% if user.admin_of_project?(@project) %>
                    <%= link_to "Remove as Admin", user_project_path(user.find_user_project(@project), user_project: { admin: false }), method: "put", class: "button button-warning button-inline" %>
                  <% else %>
                    <%= link_to "Set as Admin", user_project_path(user.find_user_project(@project), user_project: { admin: true }), method: "put", class: "button button-primary button-inline" %>
                  <% end %>
                </td>
                <td><%= user.conversations_by_project(@project).count %></td>
                <td><%= user.messages_by_project(@project).count %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</section>

app/views/projects/projects_data.html.erb
<%= render partial: "layouts/admin_header" %>
<section class="owner-data">
  <div class="container">
    <div class="row">
      <div class="twelve columns">

        <div class="table-wrapper">
          <h4>All Projects</h4>
          <table class="tablesorter">
            <thead>
              <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Token</th>
                <th>Active?</th>
                <th>Date Created</th>
              </tr>
            </thead>
            <% @projects.each do |project| %>
              <tr>
                <td><%= project.id %></td>
                <td><%= link_to project.name, project_owner_data_project_path(project) %></td>
                <td><%= project.token %></td>
                <td><%= project.active %></td>
                <td><%= project.creation_date %></td>
              </tr>
            <% end %>
          </table>
        </div>

      </div>
    </div>
  </div>
</section>